---
latitude: 41.82337
longitude: -71.41602
map_zoom: 12
name: The Dean Hotel
email: alex@traveltripper.com
phone_number: 001-111-1111
address:
  street1: 122 Fountain Street
  street2: ''
  state: Rhode Island
  city: Providence
  country: United States
  zip_code: 02903
_hotel_id: THE335
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt
